export const KV_KEYS = {
  fbAuth: (userId: string | number) => `fb_auth:${userId}`,
  facebookAuth: (userId: string | number) => `facebook-auth:${userId}`,
  projectsByUser: (userId: string | number) => `projects_by_user:${userId}`,
  freeChat: (chatId: number | string) => `free-chats:${chatId}`,
  occupiedChat: (chatId: number | string) => `occupied-chats:${chatId}`,
  config: (name: string) => `config:${name}`,
  user: (telegramId: string | number) => `user:${telegramId}`,
  project: (projectId: string) => `project:${projectId}`,
  billing: (projectId: string) => `billing:${projectId}`,
  alerts: (projectId: string) => `alerts:${projectId}`,
  autoreports: (projectId: string) => `autoreports:${projectId}`,
  projectSettings: (projectId: string) => `project-settings:${projectId}`,
  metaToken: (facebookUserId: string) => `meta-token:${facebookUserId}`,
  metaCache: (projectId: string, scope: string) => `meta-cache:${projectId}:${scope}`,
  metaLeadForms: (accountId: string) => `meta-lead-forms:${accountId}`,
  portalSession: (sessionId: string) => `portal-session:${sessionId}`,
  portalSyncState: (projectId: string) => `portal-sync:${projectId}`,
  telemetry: (key: string) => `telemetry:${key}`,
  botSession: (telegramId: number | string) => `bot-session:${telegramId}`,
  reportState: (projectId: string) => `report-state:${projectId}`,
  alertState: (projectId: string, type: string) => `alert-state:${projectId}:${type}`,
} as const;

export const KV_PREFIXES = {
  fbAuth: "fb_auth:",
  facebookAuth: "facebook-auth:",
  projectsByUser: "projects_by_user:",
  freeChats: "free-chats:",
  occupiedChats: "occupied-chats:",
  billing: "billing:",
  alerts: "alerts:",
  autoreports: "autoreports:",
  projects: "project:",
  projectSettings: "project-settings:",
  metaTokens: "meta-token:",
  metaCache: "meta-cache:",
  metaLeadForms: "meta-lead-forms:",
  portalSessions: "portal-session:",
  portalSyncState: "portal-sync:",
  botSessions: "bot-session:",
  reportStates: "report-state:",
  alertStates: "alert-state:",
} as const;
