import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const root = resolve("src", "admin");

async function load(file) {
  return readFile(resolve(root, file), "utf8");
}

async function main() {
  const template = await load("index.html");
  const style = await load("style.css");
  const api = await load("api.js");
  const script = await load("script.js");

  const html = template
    .replace("/*STYLE_PLACEHOLDER*/", style)
    .replace("/*SCRIPT_PLACEHOLDER*/", `${api}\n${script}`);

  const ts = `// This file is generated by scripts/embed-admin.mjs.\n// Do not edit it manually — edit the HTML/CSS/JS sources instead.\nconst html = ${JSON.stringify(html)};\n\nexport function renderAdminPage() {\n  return new Response(html, {\n    headers: {\n      \"content-type\": \"text/html; charset=utf-8\",\n      \"cache-control\": \"no-store\",\n    },\n  });\n}\n`;

  await writeFile(resolve(root, "page.ts"), ts, "utf8");
}

main().catch((error) => {
  console.error("Failed to embed admin assets", error);
  process.exitCode = 1;
});
